services:
  kvs:
    image: mirror.gcr.io/valkey/valkey:8
    ports:
      - "6379:6379"
    restart: unless-stopped
  mcp-dice:
    build:
      context: ./mcp/dice
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/mcp"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
  mcp-uuid:
    build:
      context: ./mcp/uuid
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/mcp"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
